tenant:
    db:
        host: '%env.TENANT_DB_HOST%'
        port: '5432'
        user: '%env.TENANT_DB_USER%'
        password: '%env.TENANT_DB_PASSWORD%'
        database: '%env.TENANT_DB_NAME%'

projects:
    - uuid: 1635399a-de76-4101-bd14-82d67e9d2574
      slug: blog
      name: Blog
      stages:
          - uuid: 01c8f908-6f48-4ef3-9751-9989931b42eb
            slug: prod
            name: Production
            migration: '2018-11-05-141146'
          - uuid: e8b8963c-49a0-46f7-89c3-e13f97cc9d77
            slug: prod-preview
            name: Production Preview
            migration: '2018-11-05-141146'
      dbCredentials:
        host: '%env.BLOG_DB_HOST%'
        port: '5432'
        user: '%env.BLOG_DB_USER%'
        password: '%env.BLOG_DB_PASSWORD%'
        database: '%env.BLOG_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'dev'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
    - uuid: 2b71cf74-5271-4142-b258-b2ce14722187
      slug: mangoweb
      name: manGoweb
      stages:
          - uuid: 7c78c41a-6a71-4adc-ae9a-0b8592480619
            slug: preview
            name: Preview
            migration: '2019-02-08-132426'
      dbCredentials:
        host: '%env.MANGOWEB_DB_HOST%'
        port: '5432'
        user: '%env.MANGOWEB_DB_USER%'
        password: '%env.MANGOWEB_DB_PASSWORD%'
        database: '%env.MANGOWEB_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'mangoweb'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
    - uuid: 9b5f50a8-c35b-46fc-abf6-090c7a68edd5
      slug: quanti
      name: Quanti
      stages:
        - uuid: bac2b042-6b65-47fd-9cb6-ba04a589c241
          slug: prod
          name: Production
          migration: '2019-02-05-182743'
      dbCredentials:
        host: '%env.QUANTI_DB_HOST%'
        port: '5432'
        user: '%env.QUANTI_DB_USER%'
        password: '%env.QUANTI_DB_PASSWORD%'
        database: '%env.QUANTI_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'quanti'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'

server:
    port: '%env.SERVER_PORT%'
