tenant:
    db:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'tenant'

projects:
    - id: 1635399a-de76-4101-bd14-82d67e9d2574
      slug: blog
      name: Blog
      stages:
          - id: 01c8f908-6f48-4ef3-9751-9989931b42eb
            slug: prod
            name: Production
          - id: e8b8963c-49a0-46f7-89c3-e13f97cc9d77
            slug: prod-preview
            name: Production Preview
            base: prod
      dbCredentials:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'cms-blog'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'dev'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
    - id: 2b71cf74-5271-4142-b258-b2ce14722187
      slug: mangoweb
      name: manGoweb
      stages:
          - id: 7c78c41a-6a71-4adc-ae9a-0b8592480619
            slug: preview
            name: Preview
      dbCredentials:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'cms-mangoweb'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'dev'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
    - id: 9b5f50a8-c35b-46fc-abf6-090c7a68edd5
      slug: quanti
      name: Quanti
      stages:
        - id: bac2b042-6b65-47fd-9cb6-ba04a589c241
          slug: prod
          name: Production
      dbCredentials:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'cms-quanti'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'dev/quanti'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'

server:
    port: '%env.SERVER_PORT%'
