tenant:
    db:
        host: '%env.TENANT_DB_HOST%'
        port: '5432'
        user: '%env.TENANT_DB_USER%'
        password: '%env.TENANT_DB_PASSWORD%'
        database: '%env.TENANT_DB_NAME%'

projects:
    - uuid: 2b71cf74-5271-4142-b258-b2ce14722187
      slug: mangoweb
      name: manGoweb
      stages:
          - uuid: 7c78c41a-6a71-4adc-ae9a-0b8592480619
            slug: preview
            name: Preview
            migration: '2019-03-08-151754'
      dbCredentials:
        host: '%env.MANGOWEB_DB_HOST%'
        port: '5432'
        user: '%env.MANGOWEB_DB_USER%'
        password: '%env.MANGOWEB_DB_PASSWORD%'
        database: '%env.MANGOWEB_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'mangoweb'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
    - uuid: 9b5f50a8-c35b-46fc-abf6-090c7a68edd5
      slug: quanti
      name: Quanti
      stages:
        - uuid: bac2b042-6b65-47fd-9cb6-ba04a589c241
          slug: prod
          name: Production
          migration: '2019-03-13-143023'
      dbCredentials:
        host: '%env.QUANTI_DB_HOST%'
        port: '5432'
        user: '%env.QUANTI_DB_USER%'
        password: '%env.QUANTI_DB_PASSWORD%'
        database: '%env.QUANTI_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'quanti'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'

server:
    port: '%env.SERVER_PORT%'
