stages:
  - test:build
  - test:run

build:
  stage: test:build
  image: node:10

  script:
    - npm install
    - npm run bootstrap
    - npm run build

  artifacts:
    paths:
      - mangoweb/admin/node_modules
      - mangoweb/cms-api/dist
      - mangoweb/cms-api/node_modules
      - node_modules
      - packages/cms-api/dist
      - packages/cms-api/node_modules
      - packages/cms-common/dist
      - packages/cms-common/node_modules
      - packages/cms-client/dist
      - packages/cms-client/node_modules

test:pkg:api:
  stage: test:run
  image: node:10

  script:
    - npm run test

lint:prettier:
  stage: test:build
  image: node:10
  script:
    - npm install
    - npm run prettier:lint
