stages:
  - test:build
  - test:run
  - deploy:build
  - deploy:helm

variables:
  DOCKER_HOST: tcp://gitlab-prod-dind-svc:2375

build:
  stage: test:build
  image: node:10

  script:
    - npm install
    - npm run bootstrap
    - npm run build

  artifacts:
    paths:
      - mangoweb/admin/node_modules
      - mangoweb/admin/public
      - mangoweb/cms-api/dist
      - mangoweb/cms-api/node_modules
      - node_modules
      - packages/cms-admin/dist
      - packages/cms-admin/node_modules
      - packages/cms-admin-server/dist
      - packages/cms-admin-server/node_modules
      - packages/cms-api/dist
      - packages/cms-api/node_modules
      - packages/cms-client/dist
      - packages/cms-client/node_modules
      - packages/cms-common/dist
      - packages/cms-common/node_modules
      - packages/cms-server-common/dist
      - packages/cms-server-common/node_modules

test:
  stage: test:run
  image: node:10

  script:
    - npm run test

prettier:
  stage: test:run
  image: node:10
  script:
    - npm run prettier:lint

build:docker:
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/mangoweb/docker-ecr:1.1
  stage: deploy:build
  only:
    refs:
      - /^deploy\/.*$/
  variables:
    VERSION: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
  script:
    - sh deploy/resolve-nodemodules.sh
    - sh deploy/build.sh

deploy:beta:api:
  stage: deploy:helm
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/deploy:5.18
  dependencies: []

  only:
    refs:
      - deploy/beta
  variables:
    GIT_STRATEGY: none # do not clone repo
    MGW_CLUSTER: beta
    RELEASE_NAME: cms-beta-api
    VALUES: '{"version": "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"}'

  environment:
    name: beta-api
    url: https://cms-api.mgw.cz

  script:
    - /usr/bin/deploy


deploy:beta:admin:
  stage: deploy:helm
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/deploy:5.18
  dependencies: []

  only:
    refs:
      - deploy/beta

  variables:
    GIT_STRATEGY: none # do not clone repo
    MGW_CLUSTER: beta
    RELEASE_NAME: cms-beta-admin
    VALUES: '{"version": "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"}'

  environment:
    name: beta-admin
    url: https://cms-admin.mgw.cz

  script:
    - /usr/bin/deploy
