stages:
  - test:build
  - test:run
  - deploy:build
  - deploy:helm
variables:
  DOCKER_HOST: tcp://gitlab-prod-dind-svc:2375
build:
  stage: test:build
  image: node:12

  script:
    - npm ci
    - npm run bootstrap
    - rm -rf {instances,projects}/*/{admin,api}/node_modules/typescript packages/*/node_modules/typescript
    - rm -rf {instances,projects}/*/{admin,api}/node_modules/.bin/{tsc,tsserver} packages/*/node_modules/.bin/{tsc,tsserver}
    - npm run build

  artifacts:
    paths:
      - "instances/*/admin/public"
      - "instances/*/admin/webpack-assets.json"
      - "instances/*/*/node_modules"
      - "instances/*/*/dist"
      - "node_modules"
      - "packages/*/dist"
      - "packages/*/node_modules"
      - "projects/*/*/dist"
      - "projects/*/*/node_modules"

test:
  stage: test:run
  image: node:12
  services:
    - postgres:10
  variables:
    TEST_DB_HOST: 127.0.0.1
    TEST_DB_PASSWORD: "123"
    TEST_DB_USER: cms_test
    TEST_DB_NAME: cms_test
    TEST_DB_PORT: 5432
    POSTGRES_USER: cms_test
    POSTGRES_DB: cms_test
    POSTGRES_PASSWORD: "123"

  script:
    - npm run test

eslint:
  stage: test:run
  image: node:12
  script:
    - npm run eslint:lint

build:docker:
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/mangoweb/docker-ecr:1.1
  stage: deploy:build
  only:
    refs:
      - /^deploy\/.*$/
  variables:
    VERSION: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
  script:
    - sh deploy/resolve-nodemodules.sh
    - sh deploy/build.sh

deploy:beta:api:
  stage: deploy:helm
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/deploy:5.18
  dependencies: []

  only:
    refs:
      - deploy/beta
  variables:
    GIT_STRATEGY: none # do not clone repo
    MGW_CLUSTER: beta
    RELEASE_NAME: cms-beta-api
    VALUES: '{"version": "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"}'

  environment:
    name: beta-api
    url: https://cms-api.mgw.cz

  script:
    - /usr/bin/deploy


deploy:beta:admin:
  stage: deploy:helm
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/deploy:5.18
  dependencies: []

  only:
    refs:
      - deploy/beta

  variables:
    GIT_STRATEGY: none # do not clone repo
    MGW_CLUSTER: beta
    RELEASE_NAME: cms-beta-admin
    VALUES: '{"version": "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"}'

  environment:
    name: beta-admin
    url: https://cms-admin.mgw.cz

  script:
    - /usr/bin/deploy


deploy:prod:api:
  stage: deploy:helm
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/deploy:5.18
  dependencies: []

  only:
    refs:
      - deploy/prod
  variables:
    GIT_STRATEGY: none # do not clone repo
    MGW_CLUSTER: prod
    RELEASE_NAME: cms-prod-api
    VALUES: '{"version": "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"}'

  environment:
    name: prod-api
    url: https://cms-api-prod.mgw.cz

  script:
    - /usr/bin/deploy


deploy:prod:admin:
  stage: deploy:helm
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/deploy:5.18
  dependencies: []

  only:
    refs:
      - deploy/prod

  variables:
    GIT_STRATEGY: none # do not clone repo
    MGW_CLUSTER: prod
    RELEASE_NAME: cms-prod-admin
    VALUES: '{"version": "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"}'

  environment:
    name: prod-admin
    url: https://cms-admin-prod.mgw.cz

  script:
    - /usr/bin/deploy

build:pilsner:
  image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/mangoweb/docker-ecr:1.1
  stage: deploy:build
  only:
    refs:
      - build/pilsner
  variables:
    VERSION: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
  script:
    - sh deploy/resolve-nodemodules.sh
    - ./deploy/build.sh pilsner
