stages:
  - test:init
  - test:build
  - test:run

init:
  stage: test:init
  image: node:10

  script:
    - npx lerna bootstrap

  artifacts:
    paths:
      - node_modules
      - mangoweb/admin/node_modules
      - mangoweb/cms-api/node_modules
      - packages/cms-api/node_modules


build:
  stage: test:build
  image: node:10

  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      - packages/cms-api/dist
      - mangoweb/cms-api/dist


test:pkg:api:
  stage: test:run
  image: node:10

  script:
    - cd packages/cms-api
    - npm test
