image: node:10
stages:
  - build
  - test
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

build:
  stage: build
  before_script:
  - cd packages/projects/blog
  script:
  - yarn install
  - tsc -p .

test:
  stage: test
  before_script:
  - cd packages/projects/blog
  script:
  - ./node_modules/.bin/mocha --require ts-node/register  --ui bdd ./tests/*.ts

lint:
  stage: test
  before_script:
  - cd packages/projects/blog
  script:
  - ./node_modules/.bin/tslint --project .
