tenant:
  db:
    host: '%env.DB_HOST%'
    port: '%env.DB_PORT::number%'
    user: '%env.DB_USER%'
    password: '%env.DB_PASSWORD%'
    database: '%env.DB_NAME%'

projects:
  - slug: pilsner
    directory: "@mangoweb/contember-project-pilsner-api"
    name: Pilsner
    stages:
      - slug: prod
        name: Production
#      - slug: preview
#        name: Preview
#        base: prod
    dbCredentials:
      host: '%env.DB_HOST%'
      port: '%env.DB_PORT::number%'
      user: '%env.DB_USER%'
      password: '%env.DB_PASSWORD%'
      database: '%env.DB_NAME%'
    s3:
      bucket: '%env.S3_BUCKET%'
      prefix: ''
      region: ''
      endpoint: '%env.S3_ENDPOINT%'
      credentials:
        key: '%env.S3_KEY%'
        secret: '%env.S3_SECRET%'
  - slug: pilsner-beta
    directory: "@mangoweb/contember-project-pilsner-api"
    name: Pilsner beta
    stages:
      - slug: beta
        name: Beta
    dbCredentials:
      host: '%env.DB_HOST%'
      port: '%env.DB_PORT::number%'
      user: '%env.DB_USER%'
      password: '%env.DB_PASSWORD%'
      database: '%env.DB_NAME%'
    s3:
      bucket: '%env.S3_BUCKET%'
      prefix: ''
      region: ''
      endpoint: '%env.S3_ENDPOINT%'
      credentials:
        key: '%env.S3_KEY%'
        secret: '%env.S3_SECRET%'
server:
  port: '%env.SERVER_PORT::number%'
