tenant:
    db:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT::number%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'tenant'

projects:
    - slug: mangoweb
      name: manGoweb
      directory: "@mangoweb/contember-project-mangoweb-api"
      stages:
          - slug: preview
            name: Preview
      dbCredentials:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT::number%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'cms-mangoweb'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'dev'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
    - slug: quanti
      name: Quanti
      directory: "@mangoweb/contember-project-quanti-api"
      stages:
        - slug: prod
          name: Production
      dbCredentials:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT::number%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'cms-quanti'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'dev/quanti'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'

    - slug: pilsner
      name: Pilsner
      directory: "@mangoweb/contember-project-pilsner-api"
      stages:
        - slug: prod
          name: Production
      dbCredentials:
        host: '%env.DB_HOST%'
        port: '%env.DB_PORT::number%'
        user: '%env.DB_USER%'
        password: '%env.DB_PASSWORD%'
        database: 'cms-pilsner'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'dev/pilsner'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
server:
    port: '%env.SERVER_PORT::number%'
