tenant:
    db:
        host: '%env.TENANT_DB_HOST%'
        port: 5432
        user: '%env.TENANT_DB_USER%'
        password: '%env.TENANT_DB_PASSWORD%'
        database: '%env.TENANT_DB_NAME%'

projects:
    - slug: mangoweb
      name: manGoweb
      directory: "@mangoweb/contember-project-mangoweb-api"
      stages:
          - slug: preview
            name: Preview
      dbCredentials:
        host: '%env.MANGOWEB_DB_HOST%'
        port: 5432
        user: '%env.MANGOWEB_DB_USER%'
        password: '%env.MANGOWEB_DB_PASSWORD%'
        database: '%env.MANGOWEB_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'mangoweb'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
    - slug: quanti
      name: Quanti
      directory: "@mangoweb/contember-project-quanti-api"
      stages:
        - slug: prod
          name: Production
      dbCredentials:
        host: '%env.QUANTI_DB_HOST%'
        port: 5432
        user: '%env.QUANTI_DB_USER%'
        password: '%env.QUANTI_DB_PASSWORD%'
        database: '%env.QUANTI_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'quanti'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'

    - slug: pilsner-beta
      directory: "@mangoweb/contember-project-pilsner-api"
      name: Pilsner Beta
      stages:
        - slug: prod
          name: Production
      dbCredentials:
        host: '%env.PILSNER_BETA_DB_HOST%'
        port: 5432
        user: '%env.PILSNER_BETA_DB_USER%'
        password: '%env.PILSNER_BETA_DB_PASSWORD%'
        database: '%env.PILSNER_BETA_DB_NAME%'
      s3:
        bucket: 'cms-api.mgw.cz'
        prefix: 'beta/pilsner'
        region: 'eu-central-1'
        credentials:
          key: 'AKIAIO53JZYNOKXXYMDA'
          secret: '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'
server:
    port: '%env.SERVER_PORT::number%'
