name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [9.6, 10, 11, 12, 13]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - name: "Install yarn deps"
        run: yarn install
      - name: "Run linter"
        run: yarn run eslint:lint
      - name: "Build app"
        run: yarn run build
      - name: Fill env
        run: echo "CONTEMBER_TENANT_MIGRATIONS_DIR=`pwd`/packages/engine-tenant-api/src/migrations" >> $GITHUB_ENV
      - name: "Run tests"
        run: yarn run test
        env:
          TEST_DB_HOST: 127.0.0.1
          TEST_DB_PASSWORD: postgres
          TEST_DB_USER: postgres
          TEST_DB_NAME: cms_test
          TEST_DB_NAME_TENANT: cms_test_tenant
          TEST_DB_PORT: 5432
          CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
          CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
