name: Publish Canary build
on:
  workflow_dispatch:

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get the version
        run: echo "VERSION=${GITHUB_SHA:10}" >> $GITHUB_ENV

      - name: "Install yarn deps"
        run: yarn install

      - name: "Build app"
        run: yarn run build

      - name: "Publish Docker"
        run: bash ./scripts/docker/publish-canary.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
